# Generated by Django 4.2.2 on 2023-07-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='subject',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
