# Generated by Django 4.2.2 on 2023-07-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_myuser_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='name',
            new_name='fullname',
        ),
    ]
